Style/Documentation:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: hash_rockets
Metrics/MethodLength:
  Max: 13
Metrics/LineLength:
  Max: 106
Style/NumericLiterals:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
